"""Figures. Every one is regenerated by run_all.py; none is hand-edited."""
from __future__ import annotations

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt          # noqa: E402
import numpy as np                        # noqa: E402
import pandas as pd                       # noqa: E402

from . import config as C                 # noqa: E402
from . import metrics as M                # noqa: E402

INK = "#1b1b1f"
MUTED = "#8a8f98"
ACCENT = "#c2410c"
PALETTE = {
    "none (biased baseline)": "#111827",
    "parcelling": "#c2410c",
    "fuzzy": "#b45309",
    "ipw": "#0e7490",
    "heckman": "#4338ca",
}
LABEL = {
    "none (biased baseline)": "no correction",
    "parcelling": "parcelling",
    "fuzzy": "fuzzy augmentation",
    "ipw": "inverse propensity",
    "heckman": "Heckman (bivariate probit)",
}
CUTOFF_TITLE = {
    "risk_hard": "Risk-based cutoff (hard threshold)",
    "risk_soft": "Risk-based cutoff (with override noise)",
    "random": "NULL CASE: random cutoff (no selection bias exists)",
}


def _style(ax, title=None, xlabel=None, ylabel=None):
    ax.spines[["top", "right"]].set_visible(False)
    ax.spines[["left", "bottom"]].set_color(MUTED)
    ax.tick_params(colors=MUTED, labelsize=9)
    if title:
        ax.set_title(title, color=INK, fontsize=11, loc="left", pad=10)
    if xlabel:
        ax.set_xlabel(xlabel, color=INK, fontsize=9.5)
    if ylabel:
        ax.set_ylabel(ylabel, color=INK, fontsize=9.5)
    ax.grid(True, alpha=0.18, linewidth=0.7)
    ax.set_axisbelow(True)


def _save(fig, name):
    path = C.FIGURES / name
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="white")
    plt.close(fig)
    return path


# --------------------------------------------------------------------------
def fig_overlap(acc: pd.DataFrame, rej: pd.DataFrame):
    fig, axes = plt.subplots(1, 3, figsize=(13.5, 3.9))

    ax = axes[0]
    bins = np.linspace(300, 900, 61)
    ax.hist(acc["risk_score"].dropna(), bins=bins, density=True, alpha=0.75,
            color="#0e7490", label=f"accepted (n={acc['risk_score'].notna().sum():,})")
    ax.hist(rej["risk_score"].dropna(), bins=bins, density=True, alpha=0.55,
            color=ACCENT, label=f"declined (n={rej['risk_score'].notna().sum():,})")
    floor = float(acc["risk_score"].quantile(0.01))
    ax.axvline(floor, color=INK, ls="--", lw=1.2)
    ax.annotate(f"accepted 1st pctile\n{floor:.0f}", (floor, ax.get_ylim()[1] * 0.72),
                xytext=(6, 0), textcoords="offset points", fontsize=8, color=INK)
    _style(ax, "Bureau score: almost no overlap", "risk score", "density")
    ax.legend(frameon=False, fontsize=8)

    ax = axes[1]
    bins = np.linspace(0, 100, 51)
    ax.hist(acc["dti"].dropna(), bins=bins, density=True, alpha=0.75,
            color="#0e7490", label="accepted")
    ax.hist(rej["dti"].dropna(), bins=bins, density=True, alpha=0.55,
            color=ACCENT, label="declined")
    _style(ax, "Debt-to-income", "DTI (%)", "density")
    ax.legend(frameon=False, fontsize=8)

    ax = axes[2]
    fields = C.COMMON_FEATURES + C.COMMON_CATEGORICAL
    miss = [100 * rej[f].isna().mean() for f in fields]
    missa = [100 * acc[f].isna().mean() for f in fields]
    yy = np.arange(len(fields))
    ax.barh(yy + 0.2, missa, height=0.38, color="#0e7490", label="accepted")
    ax.barh(yy - 0.2, miss, height=0.38, color=ACCENT, label="declined")
    ax.set_yticks(yy)
    ax.set_yticklabels(fields, fontsize=8.5)
    for y, v in zip(yy - 0.2, miss):
        if v > 1:
            ax.text(v + 1, y, f"{v:.0f}%", va="center", fontsize=8, color=ACCENT)
    _style(ax, "Missingness on the shared fields", "% missing")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    return _save(fig, "01_overlap.png")


def fig_baseline(y, pd_hat, title="Baseline scorecard (accepted loans only)"):
    fig, axes = plt.subplots(1, 2, figsize=(10, 4))
    fpr, tpr = M.roc_curve(y, pd_hat)
    g = M.gini(y, pd_hat)
    ax = axes[0]
    ax.plot(fpr, tpr, color="#0e7490", lw=2)
    ax.plot([0, 1], [0, 1], color=MUTED, ls="--", lw=1)
    ax.text(0.55, 0.15, f"AUC {M.auc(y, pd_hat):.4f}\nGini {g:.4f}",
            fontsize=10, color=INK)
    _style(ax, "ROC", "false positive rate", "true positive rate")

    ax = axes[1]
    ax.plot(np.linspace(0, 1, len(tpr)), tpr, color="#0e7490", lw=2, label="bads")
    ax.plot(np.linspace(0, 1, len(fpr)), fpr, color=ACCENT, lw=2, label="goods")
    k = np.argmax(np.abs(tpr - fpr))
    ax.vlines(np.linspace(0, 1, len(tpr))[k], fpr[k], tpr[k], color=INK, lw=1.5)
    ax.text(0.05, 0.9, f"KS {M.ks(y, pd_hat):.4f}", fontsize=10, color=INK)
    _style(ax, "KS separation", "population ordered by score", "cumulative share")
    ax.legend(frameon=False, fontsize=8)
    fig.suptitle(title, color=INK, fontsize=11, x=0.02, ha="left")
    fig.tight_layout()
    return _save(fig, "02_baseline.png")


# --------------------------------------------------------------------------
def _sweep_panel(ax, sub, ycol, sdcol, zero_line=True):
    for method, g in sub.groupby("method"):
        g = g.sort_values("rejection_rate")
        c = PALETTE.get(method, MUTED)
        ax.plot(100 * g["rejection_rate"], g[ycol], "-o", color=c, lw=1.8,
                ms=4, label=LABEL.get(method, method))
        if sdcol in g:
            ax.fill_between(100 * g["rejection_rate"], g[ycol] - g[sdcol],
                            g[ycol] + g[sdcol], color=c, alpha=0.13, lw=0)
    if zero_line:
        ax.axhline(0, color=INK, lw=1, ls="--")


def fig_sweep(summary: pd.DataFrame, ycol="bad_rate_bias",
              sdcol="bad_rate_bias_sd", name="03_sweep_bad_rate.png",
              ylabel="bias in estimated bad rate (pp)", scale=100.0,
              suptitle="Bias in the estimated through-the-door bad rate"):
    cts = [c for c in ("risk_hard", "risk_soft", "random")
           if c in set(summary["cutoff_type"])]
    fig, axes = plt.subplots(1, len(cts), figsize=(4.6 * len(cts), 4.1),
                             sharey=True)
    axes = np.atleast_1d(axes)
    for ax, ct in zip(axes, cts):
        sub = summary[summary["cutoff_type"] == ct].copy()
        sub = sub.assign(**{ycol: sub[ycol] * scale,
                            sdcol: sub[sdcol] * scale})
        _sweep_panel(ax, sub, ycol, sdcol)
        _style(ax, CUTOFF_TITLE.get(ct, ct), "rejection rate (%)",
               ylabel if ax is axes[0] else None)
        if ct == "random":
            ax.set_facecolor("#fdf6f0")
    axes[-1].legend(frameon=False, fontsize=8.5, loc="upper left")
    fig.suptitle(suptitle, color=INK, fontsize=12, x=0.02, ha="left")
    fig.tight_layout()
    return _save(fig, name)


def fig_gini_levels(summary: pd.DataFrame):
    """What each method claims its Gini is, versus what it actually delivers."""
    cts = [c for c in ("risk_hard", "risk_soft", "random")
           if c in set(summary["cutoff_type"])]
    fig, axes = plt.subplots(1, len(cts), figsize=(4.6 * len(cts), 4.1),
                             sharey=True)
    axes = np.atleast_1d(axes)
    for ax, ct in zip(axes, cts):
        sub = summary[summary["cutoff_type"] == ct]
        oracle = sub.groupby("rejection_rate")["oracle_ttd_gini"].mean()
        ax.plot(100 * oracle.index, oracle.values, color=MUTED, lw=1.6,
                ls=":", label="oracle (full-information ceiling)")
        for method, g in sub.groupby("method"):
            g = g.sort_values("rejection_rate")
            c = PALETTE.get(method, MUTED)
            ax.plot(100 * g["rejection_rate"], g["actual_ttd_gini"], "-o",
                    color=c, lw=1.8, ms=4, label=LABEL.get(method, method))
        _style(ax, CUTOFF_TITLE.get(ct, ct), "rejection rate (%)",
               "actual Gini on the full population" if ax is axes[0] else None)
        if ct == "random":
            ax.set_facecolor("#fdf6f0")
    axes[-1].legend(frameon=False, fontsize=8, loc="lower left")
    fig.suptitle("What the corrected models actually deliver "
                 "(measured against hidden truth)", color=INK, fontsize=12,
                 x=0.02, ha="left")
    fig.tight_layout()
    return _save(fig, "05_gini_levels.png")


def fig_null_case(null_df: pd.DataFrame):
    fig, ax = plt.subplots(figsize=(8.2, 3.8))
    d = null_df.sort_values("mean_abs_bad_rate_bias")
    colors = [ACCENT if h else "#0e7490" for h in d["hallucinates"]]
    ax.barh(range(len(d)), 100 * d["mean_abs_bad_rate_bias"], color=colors)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels([LABEL.get(m, m) for m in d["method"]], fontsize=9)
    for i, (v, h) in enumerate(zip(100 * d["mean_abs_bad_rate_bias"],
                                   d["hallucinates"])):
        ax.text(v + 0.15, i, f"{v:.2f} pp" + ("   HALLUCINATES" if h else ""),
                va="center", fontsize=8.5,
                color=ACCENT if h else INK)
    ax.axvline(2.0, color=INK, ls="--", lw=1)
    ax.text(2.05, len(d) - 0.4, "2 pp tolerance", fontsize=8, color=INK)
    _style(ax, "Null case: a RANDOM cutoff, where the right answer is "
               "'no correction needed'",
           "mean |bias| in estimated bad rate (pp)")
    fig.tight_layout()
    return _save(fig, "06_null_case.png")


def fig_swap(econ_rows: pd.DataFrame):
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    d = econ_rows.dropna(subset=["profit_forgone_population"])
    ax = axes[0]
    x = np.arange(len(d))
    lo = (d["profit_forgone_population"] - d["profit_forgone_ci_lo"]).abs()
    hi = (d["profit_forgone_ci_hi"] - d["profit_forgone_population"]).abs()
    ax.bar(x, d["profit_forgone_population"] / 1e6,
           color=[PALETTE.get(m, MUTED) for m in d["method"]])
    ax.errorbar(x, d["profit_forgone_population"] / 1e6,
                yerr=[lo / 1e6, hi / 1e6], fmt="none", ecolor=INK,
                capsize=4, lw=1.2)
    ax.set_xticks(x)
    ax.set_xticklabels([LABEL.get(m, m) for m in d["method"]], rotation=18,
                       ha="right", fontsize=8.5)
    ax.axhline(0, color=INK, lw=1)
    _style(ax, "Estimated profit forgone at the current cutoff",
           None, "$m (90% bootstrap CI)")

    ax = axes[1]
    ax.bar(x, 100 * d["swap_in_inferred_bad_rate"],
           color=[PALETTE.get(m, MUTED) for m in d["method"]])
    ax.set_xticks(x)
    ax.set_xticklabels([LABEL.get(m, m) for m in d["method"]], rotation=18,
                       ha="right", fontsize=8.5)
    _style(ax, "Inferred bad rate of the swap-in set", None, "%")
    fig.suptitle("Part 4: what the cutoff costs - by inference method",
                 color=INK, fontsize=12, x=0.02, ha="left")
    fig.tight_layout()
    return _save(fig, "07_swap_profit.png")


def fig_geo(zres: pd.DataFrame, disp: dict):
    fig, axes = plt.subplots(1, 2, figsize=(11, 4))
    ax = axes[0]
    ax.hist(zres["z"], bins=50, color="#0e7490", alpha=0.8, density=True)
    xs = np.linspace(-6, 6, 200)
    ax.plot(xs, np.exp(-xs ** 2 / 2) / np.sqrt(2 * np.pi), color=INK, lw=1.5,
            ls="--", label="N(0,1) if risk explained everything")
    _style(ax, f"Standardised residual by 3-digit ZIP "
               f"(sd = {disp.get('sd_of_z', float('nan')):.2f}, "
               f"not 1.0)", "z", "density")
    ax.legend(frameon=False, fontsize=8)

    ax = axes[1]
    d = zres.reindex(zres["excess_rate_pp"].abs().sort_values(
        ascending=False).index).head(15).sort_values("excess_rate_pp")
    cols = [ACCENT if v > 0 else "#0e7490" for v in d["excess_rate_pp"]]
    ax.barh(range(len(d)), d["excess_rate_pp"], color=cols)
    ax.set_yticks(range(len(d)))
    ax.set_yticklabels(d["zip3"] + "xx", fontsize=8)
    ax.axvline(0, color=INK, lw=1)
    _style(ax, "Largest unexplained gaps (pp above/below risk-predicted)",
           "excess decline rate (pp)")
    fig.suptitle("Part 4c: residual geographic variation - a flag, "
                 "not a finding of discrimination",
                 color=INK, fontsize=12, x=0.02, ha="left")
    fig.tight_layout()
    return _save(fig, "08_geo.png")


def fig_rho(rho_rows: pd.DataFrame):
    """Heckman rho with confidence intervals across the sweep."""
    fig, ax = plt.subplots(figsize=(9, 4))
    for ct, g in rho_rows.groupby("cutoff_type"):
        g = g.sort_values("rejection_rate")
        c = {"risk_hard": ACCENT, "risk_soft": "#4338ca",
             "random": "#0e7490"}.get(ct, MUTED)
        ax.errorbar(100 * g["rejection_rate"], g["rho"],
                    yerr=1.96 * g["se_rho"], fmt="-o", color=c, lw=1.8, ms=4,
                    capsize=3, label=CUTOFF_TITLE.get(ct, ct))
    ax.axhline(0, color=INK, ls="--", lw=1)
    _style(ax, "Heckman selection correlation rho, with 95% intervals",
           "rejection rate (%)", "rho")
    ax.legend(frameon=False, fontsize=8.5)
    fig.tight_layout()
    return _save(fig, "04_rho.png")
